// WB04HF123/vue/src/views/Elements/Sweetalert.vue
<template>
    <ContentWrapper>
        <div class="content-heading">
            <div>SweetAlert
                <small>A Beautiful Replacement For Javascript's "alert"</small>
            </div>
        </div>
        <div class="container-fluid">
            <h4 class="page-header mt-0">Usage examples</h4>
            <div class="row">
                <div class="col-lg-9 col-xl-6">
                    <p>A basic message</p>
                </div>
                <div class="col-lg-3 col-xl-6">
                    <p>
                        <button type="button" class="btn btn-primary" @click="swalDemo1()" >Try me!</button>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-9 col-xl-6">
                    <p>A title with a text under</p>
                </div>
                <div class="col-lg-3 col-xl-6">
                    <p>
                        <button type="button" class="btn btn-primary" @click="swalDemo2()" >Try me!</button>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-9 col-xl-6">
                    <p>A success message!</p>
                </div>
                <div class="col-lg-3 col-xl-6">
                    <p>
                        <button type="button" class="btn btn-primary" @click="swalDemo3()" >Try me!</button>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-9 col-xl-6">
                    <p>A warning message, with a function attached to the &quot;Confirm&quot;-button</p>
                </div>
                <div class="col-lg-3 col-xl-6">
                    <p>
                        <button type="button" class="btn btn-primary" @click="swalDemo4()" >Try me!</button>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-9 col-xl-6">
                    <p>... and by passing a parameter, you can execute something else for &quot;Cancel&quot;.</p>
                </div>
                <div class="col-lg-3 col-xl-6">
                    <p>
                        <button type="button" class="btn btn-primary" @click="swalDemo5()" >Try me!</button>
                    </p>
                </div>
            </div>
        </div>
    </ContentWrapper>
</template>
<script>
    import swal from 'sweetalert2'

    export default {
        name: 'Sweetalert',
        methods: {
            swalDemo1() {
                swal("Here's a message!")
            },
            swalDemo2() {
                swal("Here's a message!", "It's pretty, isn't it?")
            },
            swalDemo3() {
                swal("Good job!", "You clicked the button!", "success")
            },
            swalDemo4() {
                swal({
                        title: "Are you sure?",
                        text: "You will not be able to recover this imaginary file!",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "Yes, delete it!"
                    }).then((result) => {
                        if(result.value)
                            swal("Deleted!", "Your imaginary file has been deleted.", "success");
                    });
            },
            swalDemo5() {
                swal({
                    title: "Are you sure?",
                    text: "You will not be able to recover this imaginary file!",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Yes, delete it!",
                    cancelButtonText: "No, cancel plx!"
                }).then((result) => {
                    if (result.value) {
                        swal("Deleted!", "Your imaginary file has been deleted.", "success");
                    } else {
                        swal("Cancelled", "Your imaginary file is safe :)", "error");
                    }
                });
            },
        }
    }
</script>
<style>
    body.swal2-height-auto {
        height: 100% !important;
    }
</style>

// WB04HF123/reactjs/src/components/Elements/SweetAlert.js
import React, { Component } from 'react';
import ContentWrapper from '../Layout/ContentWrapper';
import { Container, Row, Col } from 'reactstrap';

import Swal from './Swal';

class SweetAlert extends Component {

    state = {
        swalOption1: {
            title: "Here's a message!"
        },
        swalOption2: {
            title: "Here's a message!",
            text: "It's pretty, isn't it?"
        },
        swalOption3: {
            title: "Good job!",
            text: "You clicked the button!",
            type: "success"
        },
        swalOption4: {
            title: 'Are you sure?',
            text: 'Your will not be able to recover this imaginary file!',
            icon: 'warning',
            buttons: {
                cancel: true,
                confirm: {
                    text: 'Yes, delete it!',
                    value: true,
                    visible: true,
                    className: "bg-danger",
                    closeModal: true
                }
            }
        },
        swalOption5: {
            title: 'Are you sure?',
            text: 'Your will not be able to recover this imaginary file!',
            icon: 'warning',
            buttons: {
                cancel: {
                    text: 'No, cancel plx!',
                    value: null,
                    visible: true,
                    className: "",
                    closeModal: false
                },
                confirm: {
                    text: 'Yes, delete it!',
                    value: true,
                    visible: true,
                    className: "bg-danger",
                    closeModal: false
                }
            }
        }
    }

    swalCallback4(isConfirm, swal) {
        swal("Deleted!", "Your imaginary file has been deleted.", "success");
    }

    swalCallback5(isConfirm, swal) {
        if (isConfirm) {
            swal("Deleted!", "Your imaginary file has been deleted.", "success");
        } else {
            swal("Cancelled", "Your imaginary file is safe :)", "error");
        }
    }

    render() {
        return (
            <ContentWrapper>
                <div className="content-heading">
                   <div>SweetAlert
                      <small>A Beautiful Replacement For Javascript's "alert"</small>
                   </div>
                </div>
                <Container>
                    <h4 className="page-header mt-0">Usage examples</h4>
                    <Row className="mb-2">
                        <Col sm={9} lg={6}>
                            <p>A basic message</p>
                        </Col>
                        <Col sm={3} lg={6}>
                            <Swal options={this.state.swalOption1} className="btn btn-primary">Try me!</Swal>
                        </Col>
                    </Row>
                    <Row className="mb-2">
                        <Col sm={9} lg={6}>
                            <p>A title with a text under</p>
                        </Col>
                        <Col sm={3} lg={6}>
                            <Swal options={this.state.swalOption2} className="btn btn-primary">Try me!</Swal>
                        </Col>
                    </Row>
                    <Row className="mb-2">
                        <Col sm={9} lg={6}>
                            <p>A success message!</p>
                        </Col>
                        <Col sm={3} lg={6}>
                            <Swal options={this.state.swalOption3} className="btn btn-primary">Try me!</Swal>
                        </Col>
                    </Row>
                    <Row className="mb-2">
                        <Col sm={9} lg={6}>
                            <p>A warning message, with a function attached to the &quot;Confirm&quot;-button</p>
                        </Col>
                        <Col sm={3} lg={6}>
                            <Swal options={this.state.swalOption4} callback={this.swalCallback4} className="btn btn-primary">Try me!</Swal>
                        </Col>
                    </Row>
                    <Row className="mb-2">
                        <Col sm={9} lg={6}>
                            <p>... and by passing a parameter, you can execute something else for &quot;Cancel&quot;.</p>
                        </Col>
                        <Col sm={3} lg={6}>
                            <Swal options={this.state.swalOption5} callback={this.swalCallback5} className="btn btn-primary">Try me!</Swal>
                        </Col>
                    </Row>
                </Container>
            </ContentWrapper>
            );
    }

}

export default SweetAlert;
